const CartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  INCREACE_ITEMS: "INCREACE_ITEMS",
  DECREACE_ITEMS: "DECREACE_ITEMS",
};

export default CartActionTypes;
