/* const CREATE = (arr) => {
  return new Map(arr.map((v) => [v, v]));
};

export const UserActionTypes = CREATE([
  "SET_CURRENT_USER",
  "GOOGLE_SIGN_IN_START",
  "GOOGLE_SIGN_IN_SUCCESS",
  "GOOGLE_SIGN_IN_FAILURE",
  "EMAIL_SIGN_IN_START",
  "EMAIL_SIGN_IN_SUCCESS",
  "EMAIL_SIGN_IN_FAILURE",
]); */

const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  GOOGLE_SIGN_IN_START: "GOOGLE_SIGN_IN_START",
  GOOGLE_SIGN_IN_SUCCESS: "GOOGLE_SIGN_IN_SUCCESS",
  GOOGLE_SIGN_IN_FAILURE: "GOOGLE_SIGN_IN_FAILURE",
  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
  EMAIL_SIGN_IN_SUCCESS: "EMAIL_SIGN_IN_SUCCESS",
  EMAIL_SIGN_IN_FAILURE: "EMAIL_SIGN_IN_FAILURE",
  SIGN_OUT: "SIGN_OUT",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
};
export default UserActionTypes;
